# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MycsvModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('latitude_deg', models.FloatField(blank=True, null=True)),
                ('longitude_deg', models.FloatField(blank=True, null=True)),
                ('elevation_ft', models.CharField(blank=True, max_length=200, null=True)),
                ('continent', models.CharField(blank=True, max_length=200, null=True)),
                ('iso_country', models.CharField(blank=True, max_length=200, null=True)),
                ('iso_region', models.CharField(blank=True, max_length=200, null=True)),
                ('municipality', models.CharField(blank=True, max_length=200, null=True)),
                ('gps_code', models.CharField(blank=True, max_length=200, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=200, null=True)),
                ('local_code', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
