# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogBook', '0002_auto_20161121_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logfields',
            options={'verbose_name_plural': 'LogFields'},
        ),
    ]
