# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LogBook', '0003_auto_20161204_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfields',
            name='land_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
